# Generated by Django 2.2.6 on 2019-12-10 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191210_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
