# Generated by Django 3.0.3 on 2020-02-17 12:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191210_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='UUIDKeyValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=256)),
            ],
        ),
    ]
