# Generated by Django 3.0.3 on 2020-02-18 02:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200217_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
