# Generated by Django 3.0.3 on 2020-02-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='abbreviation',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
