# Generated by Django 3.0.3 on 2020-02-13 10:20
import mptt
import mptt.managers

from django.db import migrations


def create_initial_trail(apps, schema_editor):
    Trail = apps.get_model('trails', 'Trail')
    Node = apps.get_model('trails', 'Node')

    manager = mptt.managers.TreeManager()
    manager.model = Node
    mptt.register(Node, order_insertion_by=['id'])
    manager.contribute_to_class(Node, 'objects')

    trail, _ = Trail.objects.update_or_create(name='Invista nos seus sonhos')

    indices, _ = Node.objects.update_or_create(
        name='Índices',
        abbreviation='Índices',
        defaults={'trail': trail, 'is_abstract': True, 'is_path': True},
        lft=0, rght=0, level=0, tree_id=0,
    )
    Node.objects.update_or_create(
        name='Certificado de Depósito Interbancário',
        abbreviation='CDI',
        defaults={'parent': indices},
        lft=0, rght=0, level=0, tree_id=0,
    )
    Node.objects.update_or_create(
        name='Inflação',
        abbreviation='IPCA',
        defaults={'parent': indices},
        lft=0, rght=0, level=0, tree_id=0,
    )
    renda_fixa, _ = Node.objects.update_or_create(
        name='Renda Fixa',
        abbreviation='Renda Fixa',
        defaults={'parent': indices, 'is_abstract': True, 'is_path': True},
        lft=0, rght=0, level=0, tree_id=0,
    )
    Node.objects.update_or_create(
        name='Poupança',
        abbreviation='Poupança',
        defaults={'parent': renda_fixa},
        lft=0, rght=0, level=0, tree_id=0,
    )
    Node.objects.update_or_create(
        name='Tesouro Direto',
        abbreviation='TD',
        defaults={'parent': renda_fixa},
        lft=0, rght=0, level=0, tree_id=0,
    )
    Node.objects.update_or_create(
        name='Certificado de depósito bancário',
        abbreviation='CDB',
        defaults={'parent': renda_fixa},
        lft=0, rght=0, level=0, tree_id=0,
    )
    Node.objects.update_or_create(
        name='Debêntures',
        abbreviation='DEB',
        defaults={'parent': renda_fixa},
        lft=0, rght=0, level=0, tree_id=0,
    )
    Node.objects.update_or_create(
        name='Letra de Crédito Imobiliário/do Agronegócio',
        abbreviation='LCI e LCA',
        defaults={'parent': renda_fixa},
        lft=0, rght=0, level=0, tree_id=0,
    )
    Node.objects.update_or_create(
        name='Certificado de Recebíveis Imobiliários/do Agronegócio',
        abbreviation='CRI e CRA',
        defaults={'parent': renda_fixa},
        lft=0, rght=0, level=0, tree_id=0,
    )
    Node.objects.update_or_create(
        name='Letra de Câmbio',
        abbreviation='LC',
        defaults={'parent': renda_fixa},
        lft=0, rght=0, level=0, tree_id=0,
    )

    manager.rebuild()


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0002_node_abbreviation'),
    ]

    operations = [
        migrations.RunPython(create_initial_trail, migrations.RunPython.noop)
    ]
