# Generated by Django 3.0.3 on 2020-02-13 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=64)),
                ('liquidity', models.PositiveIntegerField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('profitability_type', models.IntegerField(choices=[(0, 'Prefixado'), (1, 'Pós-fixado'), (2, '+')])),
                ('profitability', models.DecimalField(decimal_places=2, max_digits=13)),
                ('index', models.IntegerField(blank=True, choices=[(0, 'SELIC'), (1, 'CDI'), (2, 'IPCA')], null=True)),
                ('rating', models.CharField(blank=True, max_length=16, null=True)),
                ('rating_agency', models.CharField(blank=True, max_length=64, null=True)),
                ('minimal_application', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.InvestmentType')),
            ],
        ),
    ]
